""" import asyncio """
""" import threading """
""" import websockets """
""" import socketio """
""""""
""""""
""""""
""" # TODO: wrap this in a class that takes in a camera """
""" async def handle_messages(websocket): """
"""     async for message in websocket: """
"""         print(message) """
"""         await websocket.send(message) """
""""""
""" async def main(): """
"""     async with serve(handle_messages, "localhost", 8079): """
"""         await asyncio.Future()  # run forever """
""""""
""" asyncio.run(main()) """
